import { Hono } from "hono";
import { cors } from "hono/cors";
import { handleAPICall, refreshCredential } from "./api_call";
import { exchangeAntigravityCode, generateAntigravityAuthUrl } from "./auth/antigravity";
import { exchangeClaudeCode, generateClaudeAuthUrl, parseClaudeTokenResponse } from "./auth/claude";
import { exchangeCodexCode, generateCodexAuthUrl, parseCodexTokenResponse } from "./auth/codex";
import { pollKimiToken, startKimiDeviceFlow } from "./auth/kimi";
import { generatePKCE, generateRandomState } from "./auth/pkce";
import {
  deleteCredential,
  deleteOAuthSession,
  getCredentialByAuthIndex,
  getCredentialById,
  getOAuthSession,
  getOrInitManagementKey,
  handleFirstVisitInit,
  isKVBound,
  listCredentials,
  saveCredential,
  saveOAuthSession,
} from "./storage";
import { APICallRequest, CredentialRecord, Env, OAuthSession, ProviderType } from "./types";
import { renderHTML } from "./ui/html";

const app = new Hono<{ Bindings: Env }>();

// Global Error Handler (Throws and formats 500 errors clearly)
app.onError((err, c) => {
  console.error("Agent Buddy Server Error:", err);
  return c.json(
    {
      status: "error",
      error: err.message || "Internal Server Error",
    },
    500
  );
});

// Enable CORS
app.use(
  "*",
  cors({
    origin: "*",
    allowMethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allowHeaders: ["Authorization", "X-Management-Key", "Content-Type", "Accept"],
    maxAge: 86400,
  })
);

// Serve Web Management UI
app.get("/", (c) => {
  return c.html(renderHTML());
});

app.get("/management.html", (c) => {
  return c.html(renderHTML());
});

// System Initialization & Status Info (Public)
app.get("/v0/system/init-info", async (c) => {
  const kvBound = isKVBound(c.env);
  if (!kvBound) {
    return c.json(
      {
        status: "error",
        kv_bound: false,
        error: "Cloudflare KV 数据库未连接或绑定丢失！请在 Cloudflare 控制台 (Workers & Pages -> agent-buddy-server -> Settings -> Bindings) 绑定 AUTH_KV 命名空间。",
        require_login: true,
      },
      500
    );
  }

  try {
    const result = await handleFirstVisitInit(c.env);

    if (result.firstVisitKey) {
      return c.json({
        status: "ok",
        first_visit: true,
        auto_generated: true,
        key: result.firstVisitKey,
        kv_bound: true,
      });
    }

    return c.json({
      status: "ok",
      first_visit: false,
      require_login: true,
      auto_generated: result.autoGenerated ?? false,
      kv_bound: true,
    });
  } catch (err: any) {
    return c.json(
      {
        status: "error",
        kv_bound: false,
        error: `KV 连接/操作异常: ${err.message || err}`,
        require_login: true,
      },
      500
    );
  }
});

// Management Auth Middleware for /v0/management/*
app.use("/v0/management/*", async (c, next) => {
  const { key: configuredKey } = await getOrInitManagementKey(c.env);

  // Extract auth key from headers, query, or cookie
  const authHeader = c.req.header("Authorization") || "";
  const xKey = c.req.header("X-Management-Key") || "";
  const queryKey = c.req.query("key") || c.req.query("management_key") || "";

  let providedKey = "";
  if (authHeader.startsWith("Bearer ")) {
    providedKey = authHeader.slice(7).trim();
  } else if (authHeader) {
    providedKey = authHeader.trim();
  } else if (xKey) {
    providedKey = xKey.trim();
  } else if (queryKey) {
    providedKey = queryKey.trim();
  }

  if (providedKey !== configuredKey) {
    return c.json({ error: "unauthorized: invalid management key" }, 401);
  }

  return await next();
});

// Verify Management Key endpoint
app.get("/v0/management/verify", (c) => {
  return c.json({ status: "ok", valid: true });
});

// 1. GET /v0/management/auth-files (Called by agent-buddy)
app.get("/v0/management/auth-files", async (c) => {
  const nameFilter = c.req.query("name")?.trim();
  const authIndexFilter = c.req.query("auth_index")?.trim();

  let creds = await listCredentials(c.env);

  if (nameFilter) {
    creds = creds.filter(
      (item) => item.name === nameFilter || item.id === nameFilter || item.name.replace(/\.json$/, "") === nameFilter
    );
  }
  if (authIndexFilter) {
    creds = creds.filter((item) => item.auth_index === authIndexFilter);
  }

  const files = creds.map((r) => ({
    id: r.id,
    auth_index: r.auth_index,
    name: r.name,
    provider: r.provider,
    type: r.type,
    status: r.status,
    disabled: r.disabled,
    project_id: r.project_id || null,
    email: r.email || null,
    account_type: r.plan_type || null,
    created_at: new Date(r.created_at).toISOString(),
    updated_at: new Date(r.updated_at).toISOString(),
  }));

  return c.json({ files });
});

// 2. POST /v0/management/api-call (Called by agent-buddy for live quota queries)
app.post("/v0/management/api-call", async (c) => {
  let body: APICallRequest;
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid JSON body" }, 400);
  }

  const res = await handleAPICall(c.env, body);
  return c.json(res, 200);
});

// 3. OAuth Initiate: OpenAI Codex
app.get("/v0/management/codex-auth-url", async (c) => {
  const { verifier, challenge } = await generatePKCE();
  const state = generateRandomState();

  const session: OAuthSession = {
    state,
    provider: "codex",
    pkce_verifier: verifier,
    created_at: Date.now(),
    expires_at: Date.now() + 15 * 60 * 1000,
    status: "pending",
  };
  await saveOAuthSession(c.env, session);

  const authUrl = generateCodexAuthUrl(state, challenge);
  return c.json({ status: "ok", url: authUrl, state });
});

// 4. OAuth Initiate: Anthropic Claude
app.get("/v0/management/anthropic-auth-url", async (c) => {
  const { verifier, challenge } = await generatePKCE();
  const state = generateRandomState();

  const session: OAuthSession = {
    state,
    provider: "claude",
    pkce_verifier: verifier,
    created_at: Date.now(),
    expires_at: Date.now() + 15 * 60 * 1000,
    status: "pending",
  };
  await saveOAuthSession(c.env, session);

  const authUrl = generateClaudeAuthUrl(state, challenge);
  return c.json({ status: "ok", url: authUrl, state });
});

// 5. OAuth Initiate: Google Antigravity
app.get("/v0/management/antigravity-auth-url", async (c) => {
  const state = generateRandomState();

  const session: OAuthSession = {
    state,
    provider: "antigravity",
    created_at: Date.now(),
    expires_at: Date.now() + 15 * 60 * 1000,
    status: "pending",
  };
  await saveOAuthSession(c.env, session);

  const authUrl = generateAntigravityAuthUrl(state);
  return c.json({ status: "ok", url: authUrl, state });
});

// 6. OAuth Initiate: Moonshot Kimi Device Flow
app.get("/v0/management/kimi-auth-url", async (c) => {
  try {
    const data = await startKimiDeviceFlow();
    const state = generateRandomState();

    const session: OAuthSession = {
      state,
      provider: "kimi",
      device_code: data.device_code,
      user_code: data.user_code,
      verification_uri: data.verification_uri,
      verification_uri_complete: data.verification_uri_complete,
      interval: data.interval,
      created_at: Date.now(),
      expires_at: Date.now() + data.expires_in * 1000,
      status: "pending",
    };
    await saveOAuthSession(c.env, session);

    return c.json({
      status: "ok",
      state,
      user_code: data.user_code,
      verification_uri: data.verification_uri,
      verification_uri_complete: data.verification_uri_complete,
      expires_in: data.expires_in,
    });
  } catch (err: any) {
    return c.json({ status: "error", error: err.message }, 500);
  }
});

// 7. Kimi Device Flow Polling
app.get("/v0/management/kimi-poll", async (c) => {
  const state = c.req.query("state");
  if (!state) {
    return c.json({ error: "missing state" }, 400);
  }

  const session = await getOAuthSession(c.env, state);
  if (!session || !session.device_code) {
    return c.json({ error: "session expired or invalid" }, 404);
  }

  const pollRes = await pollKimiToken(session.device_code);
  if (pollRes.status === "pending") {
    return c.json({ status: "pending" });
  }

  if (pollRes.status === "error") {
    return c.json({ status: "error", message: pollRes.message });
  }

  const existing = await listCredentials(c.env);
  const authIdx = `kimi-${existing.length}`;
  const credId = `kimi-${Date.now()}`;
  const credName = `kimi-${pollRes.email || "user"}.json`;

  const cred: CredentialRecord = {
    id: credId,
    auth_index: authIdx,
    name: credName,
    provider: "kimi",
    type: "kimi",
    status: "active",
    disabled: false,
    email: pollRes.email,
    plan_type: pollRes.plan_type,
    access_token: pollRes.access_token,
    refresh_token: pollRes.refresh_token,
    expires_at: Date.now() + pollRes.expires_in * 1000,
    created_at: Date.now(),
    updated_at: Date.now(),
  };

  await saveCredential(c.env, cred);
  await deleteOAuthSession(c.env, state);

  return c.json({ status: "success", completed: true, credential: cred });
});

// 8. OAuth Callback (Codex, Claude, Antigravity)
app.post("/v0/management/oauth-callback", async (c) => {
  let body: {
    provider?: string;
    redirect_url?: string;
    code?: string;
    state?: string;
    error?: string;
  };

  try {
    body = await c.req.json();
  } catch {
    return c.json({ status: "error", error: "invalid JSON body" }, 400);
  }

  let state = (body.state || "").trim();
  let code = (body.code || "").trim();
  let error = (body.error || "").trim();

  // Extract from redirect_url if provided
  if (body.redirect_url) {
    try {
      const parsedUrl = new URL(body.redirect_url);
      if (!code && parsedUrl.searchParams.has("code")) {
        code = parsedUrl.searchParams.get("code") || "";
      }
      if (!state && parsedUrl.searchParams.has("state")) {
        state = parsedUrl.searchParams.get("state") || "";
      }
      if (!error && parsedUrl.searchParams.has("error")) {
        error = parsedUrl.searchParams.get("error") || "";
      }
    } catch {
      // String parsing fallback
      const mCode = body.redirect_url.match(/[?&#]code=([^&#\s]+)/);
      if (mCode && !code) code = decodeURIComponent(mCode[1]);
      const mState = body.redirect_url.match(/[?&#]state=([^&#\s]+)/);
      if (mState && !state) state = decodeURIComponent(mState[1]);
      const mErr = body.redirect_url.match(/[?&#]error=([^&#\s]+)/);
      if (mErr && !error) error = decodeURIComponent(mErr[1]);
    }
  }

  if (error) {
    return c.json({ status: "error", error: `OAuth provider error: ${error}` }, 400);
  }

  if (!state) {
    return c.json({ status: "error", error: "state parameter is required" }, 400);
  }

  const session = await getOAuthSession(c.env, state);
  if (!session) {
    return c.json({ status: "error", error: "OAuth session not found or expired" }, 404);
  }

  const provider = (session.provider || body.provider || "").toLowerCase() as ProviderType;
  if (!code) {
    return c.json({ status: "error", error: "authorization code is required" }, 400);
  }

  try {
    const existing = await listCredentials(c.env);
    let tokenData: any;

    if (provider === "codex") {
      try {
        tokenData = await exchangeCodexCode(code, session.pkce_verifier || "");
      } catch (err: any) {
        if (
          err.message &&
          (err.message.includes("unsupported_country_region_territory") ||
            err.message.includes("Country, region, or territory not supported") ||
            err.message.includes("403"))
        ) {
          return c.json({
            status: "client_exchange_required",
            provider: "codex",
            code: code,
            verifier: session.pkce_verifier || "",
            client_id: "app_EMoamEEZ73f0CkXaXp7hrann",
            redirect_uri: "http://localhost:1455/auth/callback",
            token_url: "https://auth.openai.com/oauth/token",
            state: state,
            message: "Cloudflare 边缘节点受限，正在自动切换为浏览器直连换取 Token...",
          });
        }
        throw err;
      }
    } else if (provider === "claude") {
      try {
        tokenData = await exchangeClaudeCode(code, session.pkce_verifier || "", state);
      } catch (err: any) {
        if (err.message && err.message.includes("403")) {
          return c.json({
            status: "client_exchange_required",
            provider: "claude",
            code: code,
            verifier: session.pkce_verifier || "",
            client_id: "9d1c250a-e61b-44d9-88ed-5944d1962f5e",
            redirect_uri: "http://localhost:54545/callback",
            token_url: "https://platform.claude.com/v1/oauth/token",
            state: state,
            message: "Cloudflare 边缘节点受限，正在自动切换为浏览器直连换取 Token...",
          });
        }
        throw err;
      }
    } else if (provider === "antigravity") {
      tokenData = await exchangeAntigravityCode(code);
    } else {
      return c.json({ status: "error", error: `unsupported provider: ${provider}` }, 400);
    }

    const authIdx = `${provider}-${existing.length}`;
    const credId = `${provider}-${Date.now()}`;
    const emailSanitized = (tokenData.email || "user").replace(/[^a-zA-Z0-9@._-]/g, "");
    const credName = `${provider}-${emailSanitized}.json`;

    const cred: CredentialRecord = {
      id: credId,
      auth_index: authIdx,
      name: credName,
      provider: provider,
      type: provider,
      status: "active",
      disabled: false,
      email: tokenData.email,
      project_id: tokenData.project_id || undefined,
      plan_type: tokenData.plan_type,
      access_token: tokenData.access_token,
      refresh_token: tokenData.refresh_token,
      expires_at: Date.now() + (tokenData.expires_in || 3600) * 1000,
      created_at: Date.now(),
      updated_at: Date.now(),
    };

    await saveCredential(c.env, cred);
    await deleteOAuthSession(c.env, state);

    return c.json({
      status: "ok",
      credential: {
        id: cred.id,
        auth_index: cred.auth_index,
        name: cred.name,
        provider: cred.provider,
        email: cred.email,
        project_id: cred.project_id,
        plan_type: cred.plan_type,
      },
    });
  } catch (err: any) {
    console.error("Token exchange failed:", err);
    return c.json({ status: "error", error: err.message }, 500);
  }
});

// 8.5 Direct Save from Client-side OAuth Exchange (Bypasses Cloudflare Egress Restrictions)
app.post("/v0/management/oauth-save-token", async (c) => {
  const body = await c.req.json<{
    provider: ProviderType;
    token_data: any;
    state?: string;
  }>();

  if (!body.provider || !body.token_data) {
    return c.json({ status: "error", error: "missing provider or token_data" }, 400);
  }

  const existing = await listCredentials(c.env);
  let tokenInfo: any;

  if (body.provider === "codex") {
    tokenInfo = parseCodexTokenResponse(body.token_data);
  } else if (body.provider === "claude") {
    tokenInfo = await parseClaudeTokenResponse(body.token_data);
  } else {
    return c.json({ status: "error", error: "unsupported provider for client save" }, 400);
  }

  const authIdx = `${body.provider}-${existing.length}`;
  const credId = `${body.provider}-${Date.now()}`;
  const emailSanitized = (tokenInfo.email || "user").replace(/[^a-zA-Z0-9@._-]/g, "");
  const credName = `${body.provider}-${emailSanitized}.json`;

  const cred: CredentialRecord = {
    id: credId,
    auth_index: authIdx,
    name: credName,
    provider: body.provider,
    type: body.provider,
    status: "active",
    disabled: false,
    email: tokenInfo.email,
    plan_type: tokenInfo.plan_type,
    access_token: tokenInfo.access_token,
    refresh_token: tokenInfo.refresh_token,
    expires_at: Date.now() + (tokenInfo.expires_in || 3600) * 1000,
    created_at: Date.now(),
    updated_at: Date.now(),
  };

  await saveCredential(c.env, cred);
  if (body.state) {
    await deleteOAuthSession(c.env, body.state).catch(() => {});
  }

  return c.json({
    status: "ok",
    credential: {
      id: cred.id,
      auth_index: cred.auth_index,
      name: cred.name,
      provider: cred.provider,
      email: cred.email,
    },
  });
});

// 9. Check Auth Status / Cancel OAuth Session
app.get("/v0/management/get-auth-status", async (c) => {
  const state = c.req.query("state");
  if (!state) return c.json({ error: "missing state" }, 400);
  const session = await getOAuthSession(c.env, state);
  if (!session) return c.json({ status: "expired" }, 404);
  return c.json({ status: session.status || "pending", provider: session.provider });
});

app.delete("/v0/management/oauth-session", async (c) => {
  const state = c.req.query("state");
  if (state) await deleteOAuthSession(c.env, state);
  return c.json({ status: "ok" });
});

// 10. DELETE /v0/management/auth-files
app.delete("/v0/management/auth-files", async (c) => {
  const name = c.req.query("name") || c.req.query("id") || c.req.query("auth_index");
  if (!name) {
    return c.json({ error: "name or id is required" }, 400);
  }

  const success = await deleteCredential(c.env, name);
  if (!success) {
    return c.json({ error: "credential not found" }, 404);
  }
  return c.json({ status: "ok" });
});

// 11. PATCH /v0/management/auth-files/status (Toggle disabled)
app.patch("/v0/management/auth-files/status", async (c) => {
  const body = await c.req.json<{ name: string; disabled?: boolean }>();
  if (!body.name) return c.json({ error: "missing name" }, 400);

  const cred = await getCredentialByAuthIndex(c.env, body.name);
  if (!cred) return c.json({ error: "credential not found" }, 404);

  if (body.disabled !== undefined) {
    cred.disabled = body.disabled;
    cred.status = cred.disabled ? "disabled" : "active";
    await saveCredential(c.env, cred);
  }

  return c.json({ status: "ok" });
});

// 12. POST /v0/management/auth-files (Direct JSON Import / Upload)
app.post("/v0/management/auth-files", async (c) => {
  let raw: any;
  try {
    raw = await c.req.json();
  } catch {
    return c.json({ error: "invalid JSON body" }, 400);
  }

  const existing = await listCredentials(c.env);
  let provider: ProviderType = "codex";
  const typeStr = (raw.type || raw.provider || "").toLowerCase();

  if (typeStr.includes("claude") || typeStr.includes("anthropic")) {
    provider = "claude";
  } else if (typeStr.includes("antigravity") || typeStr.includes("cloudcode") || typeStr.includes("google")) {
    provider = "antigravity";
  } else if (typeStr.includes("kimi") || typeStr.includes("moonshot")) {
    provider = "kimi";
  } else if (typeStr.includes("codex") || typeStr.includes("openai")) {
    provider = "codex";
  }

  let accessToken = raw.access_token || raw.token || "";
  let refreshToken = raw.refresh_token || "";
  let projectId = raw.project_id || "";
  let email = raw.email || "";
  let planType = raw.plan_type || "";

  // Nested structures (e.g. token_data in Codex/Claude CLIProxyAPI bundles)
  if (raw.token_data && typeof raw.token_data === "object") {
    accessToken = raw.token_data.access_token || accessToken;
    refreshToken = raw.token_data.refresh_token || refreshToken;
    email = raw.token_data.email || email;
  }

  if (!accessToken && !refreshToken) {
    return c.json({ error: "JSON must contain access_token or refresh_token" }, 400);
  }

  const authIdx = `${provider}-${existing.length}`;
  const credId = `${provider}-${Date.now()}`;
  const credName = raw.name || `${provider}-${email ? email.replace(/[^a-zA-Z0-9@._-]/g, "") : Date.now()}.json`;

  const cred: CredentialRecord = {
    id: credId,
    auth_index: authIdx,
    name: credName,
    provider: provider,
    type: provider,
    status: "active",
    disabled: false,
    email: email || undefined,
    project_id: projectId || undefined,
    plan_type: planType || undefined,
    access_token: accessToken,
    refresh_token: refreshToken || undefined,
    expires_at: raw.expires_at || Date.now() + 3600 * 1000,
    created_at: Date.now(),
    updated_at: Date.now(),
  };

  await saveCredential(c.env, cred);
  return c.json({ status: "ok", name: cred.name, auth_index: cred.auth_index });
});

export default app;
