import { base64UrlEncode } from "./auth/pkce";
import { CredentialRecord, Env, OAuthSession } from "./types";

// In-memory fallback for local testing without KV bound
const memoryCredentials = new Map<string, CredentialRecord>();
const memorySessions = new Map<string, OAuthSession>();
let memorySystemKey = "";

const CRED_INDEX_KEY = "_credential_index";
const CRED_PREFIX = "cred:";
const SESSION_PREFIX = "session:";
const SYSTEM_KEY_STORE = "_system_management_key";

/**
 * Retrieve the active management key.
 * 1. If configured in environment variables (c.env.MANAGEMENT_KEY), use that.
 * 2. Otherwise, retrieve auto-generated key from KV database.
 * 3. If neither exists, generate a secure random key, store it in KV, and return it.
 */
export async function getOrInitManagementKey(env: Env): Promise<{ key: string; isAutoGenerated: boolean }> {
  // 1. Explicitly configured via Cloudflare Environment Variable / Secret
  if (env.MANAGEMENT_KEY && env.MANAGEMENT_KEY.trim()) {
    return { key: env.MANAGEMENT_KEY.trim(), isAutoGenerated: false };
  }

  // 2. Check persistent KV storage
  if (env.AUTH_KV) {
    try {
      const stored = await env.AUTH_KV.get(SYSTEM_KEY_STORE);
      if (stored && stored.trim()) {
        return { key: stored.trim(), isAutoGenerated: true };
      }
    } catch (e) {
      console.error("Failed to read system key from KV:", e);
    }
  } else if (memorySystemKey) {
    return { key: memorySystemKey, isAutoGenerated: true };
  }

  // 3. Auto-generate a secure random 24-character key on first run
  const randomBytes = new Uint8Array(18);
  crypto.getRandomValues(randomBytes);
  const generated = "cb_sec_" + base64UrlEncode(randomBytes);

  if (env.AUTH_KV) {
    try {
      await env.AUTH_KV.put(SYSTEM_KEY_STORE, generated);
    } catch (e) {
      console.error("Failed to persist generated key in KV:", e);
    }
  } else {
    memorySystemKey = generated;
  }

  return { key: generated, isAutoGenerated: true };
}

export async function listCredentials(env: Env): Promise<CredentialRecord[]> {
  if (!env.AUTH_KV) {
    return Array.from(memoryCredentials.values());
  }

  try {
    const indexRaw = await env.AUTH_KV.get(CRED_INDEX_KEY);
    if (!indexRaw) return [];
    const ids: string[] = JSON.parse(indexRaw);

    const records: CredentialRecord[] = [];
    for (const id of ids) {
      const raw = await env.AUTH_KV.get(`${CRED_PREFIX}${id}`);
      if (raw) {
        try {
          records.push(JSON.parse(raw));
        } catch {
          // ignore corrupted single record
        }
      }
    }
    return records;
  } catch (err) {
    console.error("Failed to list credentials from KV:", err);
    return [];
  }
}

export async function getCredentialById(env: Env, id: string): Promise<CredentialRecord | null> {
  if (!env.AUTH_KV) {
    return memoryCredentials.get(id) || null;
  }

  try {
    const raw = await env.AUTH_KV.get(`${CRED_PREFIX}${id}`);
    if (!raw) return null;
    return JSON.parse(raw);
  } catch (err) {
    console.error(`Failed to get credential ${id} from KV:`, err);
    return null;
  }
}

export async function getCredentialByAuthIndex(env: Env, authIndex: string): Promise<CredentialRecord | null> {
  const all = await listCredentials(env);
  const found = all.find(
    (c) =>
      c.auth_index === authIndex ||
      c.id === authIndex ||
      c.name === authIndex ||
      c.name.replace(/\.json$/, "") === authIndex.replace(/\.json$/, "")
  );
  return found || null;
}

export async function saveCredential(env: Env, cred: CredentialRecord): Promise<void> {
  if (!env.AUTH_KV) {
    memoryCredentials.set(cred.id, cred);
    return;
  }

  try {
    await env.AUTH_KV.put(`${CRED_PREFIX}${cred.id}`, JSON.stringify(cred));

    // Update index
    const indexRaw = await env.AUTH_KV.get(CRED_INDEX_KEY);
    let ids: string[] = indexRaw ? JSON.parse(indexRaw) : [];
    if (!ids.includes(cred.id)) {
      ids.push(cred.id);
      await env.AUTH_KV.put(CRED_INDEX_KEY, JSON.stringify(ids));
    }
  } catch (err) {
    console.error("Failed to save credential to KV:", err);
    throw err;
  }
}

export async function deleteCredential(env: Env, lookup: string): Promise<boolean> {
  const all = await listCredentials(env);
  const target = all.find(
    (c) =>
      c.id === lookup ||
      c.auth_index === lookup ||
      c.name === lookup ||
      c.name.replace(/\.json$/, "") === lookup.replace(/\.json$/, "")
  );

  if (!target) return false;

  if (!env.AUTH_KV) {
    memoryCredentials.delete(target.id);
    return true;
  }

  try {
    await env.AUTH_KV.delete(`${CRED_PREFIX}${target.id}`);
    const indexRaw = await env.AUTH_KV.get(CRED_INDEX_KEY);
    if (indexRaw) {
      let ids: string[] = JSON.parse(indexRaw);
      ids = ids.filter((id) => id !== target.id);
      await env.AUTH_KV.put(CRED_INDEX_KEY, JSON.stringify(ids));
    }
    return true;
  } catch (err) {
    console.error(`Failed to delete credential ${lookup} from KV:`, err);
    return false;
  }
}

export async function saveOAuthSession(env: Env, session: OAuthSession): Promise<void> {
  if (!env.AUTH_KV) {
    memorySessions.set(session.state, session);
    return;
  }

  try {
    // TTL in seconds (15 minutes = 900s)
    await env.AUTH_KV.put(`${SESSION_PREFIX}${session.state}`, JSON.stringify(session), {
      expirationTtl: 900,
    });
  } catch (err) {
    console.error("Failed to save OAuth session to KV:", err);
  }
}

export async function getOAuthSession(env: Env, state: string): Promise<OAuthSession | null> {
  if (!env.AUTH_KV) {
    const s = memorySessions.get(state);
    if (!s) return null;
    if (Date.now() > s.expires_at) {
      memorySessions.delete(state);
      return null;
    }
    return s;
  }

  try {
    const raw = await env.AUTH_KV.get(`${SESSION_PREFIX}${state}`);
    if (!raw) return null;
    return JSON.parse(raw);
  } catch (err) {
    console.error("Failed to get OAuth session from KV:", err);
    return null;
  }
}

export async function deleteOAuthSession(env: Env, state: string): Promise<void> {
  if (!env.AUTH_KV) {
    memorySessions.delete(state);
    return;
  }

  try {
    await env.AUTH_KV.delete(`${SESSION_PREFIX}${state}`);
  } catch (err) {
    console.error("Failed to delete OAuth session from KV:", err);
  }
}
