import { base64UrlEncode } from "./auth/pkce";
import { CredentialRecord, Env, OAuthSession } from "./types";

const CRED_INDEX_KEY = "_credential_index";
const CRED_PREFIX = "cred:";
const SESSION_PREFIX = "session:";
const SYSTEM_KEY_STORE = "_system_management_key";
const SYSTEM_FIRST_VISIT_STORE = "_system_first_visit_done";

/**
 * Retrieve bound KV namespace, supporting case variations (AUTH_KV, auth_kv, KV, kv)
 */
export function getKV(env: Env): KVNamespace | undefined {
  return env.AUTH_KV || (env as any).auth_kv || (env as any).KV || (env as any).kv;
}

export function isKVBound(env: Env): boolean {
  return !!getKV(env);
}

/**
 * Strict KV getter that throws an informative error if KV is not bound
 */
export function requireKV(env: Env): KVNamespace {
  const kv = getKV(env);
  if (!kv) {
    throw new Error(
      "Cloudflare KV 数据库未连接或绑定丢失！请在 Cloudflare 仪表盘 (Workers & Pages -> agent-buddy-server -> Settings -> Bindings) 绑定 AUTH_KV 命名空间。"
    );
  }
  return kv;
}

/**
 * Retrieve the active management key.
 * 1. If configured in environment variables (c.env.MANAGEMENT_KEY), use that.
 * 2. Otherwise, retrieve auto-generated key from KV database.
 * 3. If neither exists, generate a secure random key, store it in KV, and return it.
 */
export async function getOrInitManagementKey(env: Env): Promise<{ key: string; isAutoGenerated: boolean }> {
  // 1. Explicitly configured via Cloudflare Environment Variable / Secret
  if (env.MANAGEMENT_KEY && env.MANAGEMENT_KEY.trim()) {
    return { key: env.MANAGEMENT_KEY.trim(), isAutoGenerated: false };
  }

  const kv = requireKV(env);

  try {
    const stored = await kv.get(SYSTEM_KEY_STORE);
    if (stored && stored.trim()) {
      return { key: stored.trim(), isAutoGenerated: true };
    }
  } catch (e: any) {
    console.error("Failed to read system key from KV:", e);
    throw new Error(`读取 KV 系统密钥失败: ${e.message || e}`);
  }

  // Auto-generate a secure random 24-character key on first run
  const randomBytes = new Uint8Array(18);
  crypto.getRandomValues(randomBytes);
  const generated = "cb_sec_" + base64UrlEncode(randomBytes);

  try {
    await kv.put(SYSTEM_KEY_STORE, generated);
  } catch (e: any) {
    console.error("Failed to persist generated key in KV:", e);
    throw new Error(`写入 KV 系统密钥失败: ${e.message || e}`);
  }

  return { key: generated, isAutoGenerated: true };
}

/**
 * Handle initial setup for users who did not specify MANAGEMENT_KEY in env:
 * - On first visit: generate random key, mark first-visit done, return key.
 * - On subsequent visits: do NOT return key, require login.
 * - If env.MANAGEMENT_KEY was explicitly set: always require login, never return key.
 */
export async function handleFirstVisitInit(env: Env): Promise<{
  requireLogin: boolean;
  firstVisitKey?: string;
  autoGenerated?: boolean;
}> {
  // 1. Explicitly configured via Cloudflare Environment Variable / Secret -> never return key
  if (env.MANAGEMENT_KEY && env.MANAGEMENT_KEY.trim()) {
    return { requireLogin: true, autoGenerated: false };
  }

  const kv = requireKV(env);

  let firstVisitDone = false;
  try {
    const flag = await kv.get(SYSTEM_FIRST_VISIT_STORE);
    firstVisitDone = flag === "true";
  } catch (e: any) {
    console.error("Failed to check first visit flag:", e);
    throw new Error(`检查 KV 初始化状态失败: ${e.message || e}`);
  }

  // Subsequent visits: do NOT return key, require login
  if (firstVisitDone) {
    return { requireLogin: true, autoGenerated: true };
  }

  // First visit: get or initialize key, mark first visit completed
  const { key } = await getOrInitManagementKey(env);

  try {
    await kv.put(SYSTEM_FIRST_VISIT_STORE, "true");
  } catch (e: any) {
    console.error("Failed to write first visit flag:", e);
    throw new Error(`更新 KV 初始化标记失败: ${e.message || e}`);
  }

  return {
    requireLogin: false,
    firstVisitKey: key,
    autoGenerated: true,
  };
}

export async function listCredentials(env: Env): Promise<CredentialRecord[]> {
  const kv = requireKV(env);

  try {
    const indexRaw = await kv.get(CRED_INDEX_KEY);
    if (!indexRaw) return [];
    const ids: string[] = JSON.parse(indexRaw);

    const records: CredentialRecord[] = [];
    for (const id of ids) {
      const raw = await kv.get(`${CRED_PREFIX}${id}`);
      if (raw) {
        records.push(JSON.parse(raw));
      }
    }
    return records;
  } catch (err: any) {
    console.error("Failed to list credentials from KV:", err);
    throw new Error(`读取 KV 凭据列表失败: ${err.message || err}`);
  }
}

export async function getCredentialById(env: Env, id: string): Promise<CredentialRecord | null> {
  const kv = requireKV(env);

  try {
    const raw = await kv.get(`${CRED_PREFIX}${id}`);
    return raw ? JSON.parse(raw) : null;
  } catch (err: any) {
    console.error(`Failed to get credential ${id} from KV:`, err);
    throw new Error(`读取 KV 凭据失败: ${err.message || err}`);
  }
}

export async function getCredentialByAuthIndex(env: Env, authIndex: string): Promise<CredentialRecord | null> {
  const all = await listCredentials(env);
  return (
    all.find(
      (c) => c.auth_index === authIndex || c.name === authIndex || c.id === authIndex
    ) || null
  );
}

export async function saveCredential(env: Env, cred: CredentialRecord): Promise<void> {
  const kv = requireKV(env);

  try {
    await kv.put(`${CRED_PREFIX}${cred.id}`, JSON.stringify(cred));

    // Update credential index
    const indexRaw = await kv.get(CRED_INDEX_KEY);
    const ids: string[] = indexRaw ? JSON.parse(indexRaw) : [];
    if (!ids.includes(cred.id)) {
      ids.push(cred.id);
      await kv.put(CRED_INDEX_KEY, JSON.stringify(ids));
    }
  } catch (err: any) {
    console.error("Failed to save credential to KV:", err);
    throw new Error(`保存凭据到 KV 失败: ${err.message || err}`);
  }
}

export async function deleteCredential(env: Env, nameOrId: string): Promise<boolean> {
  const all = await listCredentials(env);
  const target = all.find((c) => c.id === nameOrId || c.name === nameOrId);
  if (!target) return false;

  const kv = requireKV(env);

  try {
    await kv.delete(`${CRED_PREFIX}${target.id}`);
    const indexRaw = await kv.get(CRED_INDEX_KEY);
    if (indexRaw) {
      const ids: string[] = JSON.parse(indexRaw);
      const updated = ids.filter((id) => id !== target.id);
      await kv.put(CRED_INDEX_KEY, JSON.stringify(updated));
    }
    return true;
  } catch (err: any) {
    console.error("Failed to delete credential from KV:", err);
    throw new Error(`删除 KV 凭据失败: ${err.message || err}`);
  }
}

export async function saveOAuthSession(env: Env, session: OAuthSession): Promise<void> {
  const kv = requireKV(env);

  try {
    await kv.put(`${SESSION_PREFIX}${session.state}`, JSON.stringify(session), {
      expirationTtl: 600, // Expire session in 10 minutes
    });
  } catch (err: any) {
    console.error("Failed to save OAuth session to KV:", err);
    throw new Error(`保存 OAuth 会话到 KV 失败: ${err.message || err}`);
  }
}

export async function getOAuthSession(env: Env, state: string): Promise<OAuthSession | null> {
  const kv = requireKV(env);

  try {
    const raw = await kv.get(`${SESSION_PREFIX}${state}`);
    return raw ? JSON.parse(raw) : null;
  } catch (err: any) {
    console.error("Failed to get OAuth session from KV:", err);
    throw new Error(`读取 OAuth 会话失败: ${err.message || err}`);
  }
}

export async function deleteOAuthSession(env: Env, state: string): Promise<void> {
  const kv = requireKV(env);

  try {
    await kv.delete(`${SESSION_PREFIX}${state}`);
  } catch (err: any) {
    console.error("Failed to delete OAuth session from KV:", err);
    throw new Error(`删除 OAuth 会话失败: ${err.message || err}`);
  }
}
